version = 0.1

[default]
[default.global.parameters]
stack_name = "stock-data-pipeline"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "stock-data-pipeline"
parameter_overrides = [
    "AlphaVantageApiKey=IRYWV66KYDTB6S2W",
    "BucketName=stock-quotes-data"
]

[default.package.parameters]
resolve_s3 = true

